### ISSUE TITLE
Cannot locate rosdep definition for [rmf_obstacle_msgs]

### ISSUE THREAD

**Issue by WangYi102** [open-rmf/rmf_obstacle_detectors#11] opened 2023-03-27 10:13 UTC

**Comment by Yadunund** [comment] 2023-03-28 03:18
See https://github.com/open-rmf/rmf_obstacle_detectors/issues/8#issuecomment-1386782158

Closing this since its a duplicate of other open tickets.

**Closed by Yadunund** 2023-03-28 03:18 UTC
Labels: bug
